spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/BD_BazaryPapeleria_DEV
spring.datasource.username=postgres
spring.datasource.password=Damian.10P
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=YmF6YXItY2hpbml0YS1qd3Qtc2VjcmV0LWtleS0yMDI2LWJhY2tlbmQtdmVyeS1zZWN1cmUtMTIz
app.jwt.expiration-ms=86400000

spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info

